spring:
  async:
    config:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 100
  config:
    import: queries.yml
  profiles:
    active: ${SPRING_PROFILE:local}
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver