### PUT upload banking csv
PUT {{DATA_RELATION_BASE_URL}}/table_queries/v1/insert
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="checking_records.csv"

< checking_records.csv

### PUT upload Credit csv
PUT {{DATA_RELATION_BASE_URL}}/table_queries/v1/insert
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="credit_records.csv"

< credit_records.csv